

import { Geist, Geist_Mono } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css';
import "./globals.css";
import Providers from "@/Components/providers/Providers";
import I18nProvider from '@/providers/I18nProvider';
// import { SessionProvider } from "next-auth/react"
// import { useSession } from "next-auth/react";

import { Toaster } from "react-hot-toast";
import '@/lib/useTranslation';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // const { data: session } = useSession();
  return (
    <Providers>
      <I18nProvider>
        {/* <SessionProvider session={session}> */}
          <html lang="en">

            <body
              className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
              <Toaster position="top-right" reverseOrder={false} />
              {children}
            </body>
          </html>
        {/* </SessionProvider> */}
      </I18nProvider>
    </Providers>
  );
}
